name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  # Many color libraries just need this to be set to any value, but at least
  # one distinguishes color depth, where "3" -> "256-bit color".
  FORCE_COLOR: 3

jobs:
  tests:
    name: Tests ${{ matrix.runs-on }} ${{ matrix.environment }}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        environment: [ci-py310, ci-py313]
        runs-on: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: prefix-dev/setup-pixi@v0.8.5
        with:
          pixi-version: v0.39.4
          cache: true
          environments: ${{ matrix.environment }}

      - name: quantity-array tests
        run: pixi run --environment=${{ matrix.environment }} tests

      - name: array-api-tests
        run: pixi run --environment=${{ matrix.environment }} xp-tests
